server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: sqlite3
    source: ./test.db?_fk=1
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
wechat:
  token: '111'
  appid: wx4edbdc4895597796
  app_secret: cea927f6ae8a5974a0ce3e266a4cad0b
tencent_cloud_video_player:
  appid: 1318517483
  app_secret: y3O31sTJnmC4BGhUrIrO
  domain: tcplayer.vcube.tencent.com # 视频防盗链设置的域名
  scheme: https # 视频防盗链设置的协议类型 http/https
