name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  IMAGE_VERSION: latest

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Get short HEAD
        id: head
        run: echo "::set-output name=head::$(git rev-parse --short HEAD)"

      - name: docker build
        env: 
          IMAGE_TAG: ${{ steps.timestamp.outputs.timestamp }}-${{ steps.head.outputs.head }}
        run: |
          docker build -t chaoyue/kubecit-service:$IMAGE_TAG -f ./Dockerfile .
          docker push chaoyue/kubecit-service:$IMAGE_TAG
